### ISSUE TITLE
강의 내용 질문있습니다

### ISSUE THREAD

**Issue by mellykim123** [hsnam95/class2023Spring#2]
복습중에 질문이 있어 이슈를 남깁니다.

첫번째로, 소리가 340m / s 를 간다고 할때, 1m에 태극무늬가 2개 있으면 170m를 간다고 제가 필기에 적어놨는데, 이부분이 잘 이해가 되지 않습니다. 만약 태극무늬가 1m 당 2개면 340m를 갈때 680번 생겨서 결론적으로 680HZ가 되는게 아닌건가요? 

두번째로, f0의 값을 그래프에서 찾는 방법에 대해 제가 이해한게 맞는지 질문드리고 싶습니다. 만약 현악기의 주파수가 100.200.300...이런식으로 증가하는 x축이고, 관악기의 주파수도 500,1000,1500... 이런식으로 magnitude가 센 형식이라면 , f1은 그래프에서 x축이 500hz 일때의 y값이고 f2는 1000hz일때의 y값이고, f0은 제일 처음 사인 곡선인 100hz의 y값인건가요? 

답변해주시면 감사합니다

**Comment by hsnam95** [comment]
첫번째로, 소리가 340m / s 를 간다고 할때, 1m에 태극무늬가 2개 있으면 170m를 간다고 제가 필기에 적어놨는데, 이부분이 잘 이해가 되지 않습니다. 만약 태극무늬가 1m 당 2개면 340m를 갈때 680번 생겨서 결론적으로 680HZ가 되는게 아닌건가요?

-- 필기에 오류가 있어 보입니다.
아래의 시뮬레이션으로 값들을 넣어 보고 확인하세요.
https://www.walter-fendt.de/html5/phen/standinglongitudinalwaves_en.htm

두번째로, f0의 값을 그래프에서 찾는 방법에 대해 제가 이해한게 맞는지 질문드리고 싶습니다. 만약 현악기의 주파수가 100.200.300...이런식으로 증가하는 x축이고, 

-- 이 때 언급하는 대상은 스펙트럼이겠죠. 

관악기의 주파수도 500,1000,1500... 이런식으로 magnitude가 센 형식이라면, f1은 그래프에서 

-- 이 때 언급하는 그래프도 스펙트럼이겠죠. 

x축이 500hz 일때의 y값이고 f2는 1000hz일때의 y값이고, 

-- y값이 아니라, x 값 그 자체입니다. 그래서 f1은 500Hz, f2는 1500Hz 그 자체가 됩니다.

f0은 제일 처음 사인 곡선인 100hz의 y값인건가요?

-- 이것도 마찬가지로 x 값인 100Hz가 f0(pitch)가 됩니다.

**Comment by mellykim123** [comment]
네 이해했습니다! 자세한 답변 감사드립니다 교수님:)
